<?php
namespace App\Ship\Migrator\Commands;

use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ListMigrations extends \App\Ship\Command\Command
{
    protected function configure()
    {
        $this->setName('migrations:list')
            ->setDescription('List all migrations on App\\Ship\\Migrations namespace!');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}
